name: presensimob
version: 2.1.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.19.0
  shared_preferences: ^2.0.6
  flutter_easyloading: ^3.0.5
  sp_util: ^2.0.3 
  flutter_map: ^2.2.0
  latlong2: ^0.8.1 
  cached_network_image: ^3.2.1
  geocoding: ^2.0.4
  carousel_slider: ^4.2.1  
  google_maps_flutter: ^2.3.0 
  geolocator: ^12.0.0
  json_annotation: ^4.8.1 
  # safe_device: ^1.1.4
  table_calendar: ^3.0.0 
  liquid_pull_to_refresh: ^3.0.1
  flutter_localization: ^0.2.0
  month_picker_dialog: ^3.0.0
  fl_chart: ^0.67.0
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^6.2.1
  
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  url_launcher: ^6.1.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - images/
    
